[[pages]]
path = "home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/main.py"
name = "Deep Bark Web App"
icon = "ğŸŒ³"

[[pages]]
path = "pages/sample.py"
name = "Bark Samples"
icon = "ğŸªµ"

[[pages]]
path = "pages/herb.py"
name = "Herbarium"
icon = "ğŸƒ"

[[pages]]
path = "pages/map.py"
name = "Location of Trees"
icon = "ğŸ—ºï¸"


